#! /bin/sh

cat <<EOD | (
arcticsecurity.com
badrap.io
cyblem.com
scanabc.com
sensorfleet.com
sensorfu.com
hownetworks.io
testaaverkkosi.fi
tracetrout.me
uriteller.io
EOD

  while read domain; do
    for prefix in http:// https:// http://www. https://www.; do
      url=$prefix$domain
      ## Return code
      returncode=$(curl -m 2 -s -I -o /dev/null -w  '%{http_code}' ${url})
      ## Redirect target
      effectiveurl=$(curl -Ls -o /dev/null -w %{url_effective} ${url})
      if [ "x${url}/" != "x${effectiveurl}" ]; then
        redirect=" -> ${effectiveurl}"
      else
        redirect=""
      fi
      ## HSTS
      strict=$(curl -s -D- ${url} | grep Strict-Transport-Security)
      if [ "x${strict}" != "x" ]; then
        hsts=" [HSTS]"
      else
        hsts=""
      fi
      ## Display
      echo ${returncode}" "${url}${redirect}${hsts}
    done
  done
)
