#! /bin/sh

cat <<EOD | (
arcticsecurity.com
badrap.io
cyblem.com
scanabc.com
sensorfleet.com
sensorfu.com
hownetworks.io
testaaverkkosi.fi
tracetrout.me
uriteller.io
EOD

  while read domain; do
    for prefix in http:// https:// http://www. https://www.; do
      url=$prefix$domain
      curl -m 2 -s -I -o /dev/null -w  '%{http_code}' ${url}
      effectiveurl=$(curl -Ls -o /dev/null -w %{url_effective} ${url})
      if [ x${url}/ != x${effectiveurl} ]; then
        redirect=" -> ${effectiveurl}"
      else
        redirect=""
      fi
      echo " "${url}${redirect}
    done
  done
)
